using System.ComponentModel;
using System.Runtime.CompilerServices;
using ITAD.LibrarySync.Core.Launchers;
using ITAD.LibrarySync.Core.Scheduling;

namespace ITAD.LibrarySync.App.Services;

public sealed class LanguageOption(string code, string displayName)
{
    public string Code { get; } = code;
    public string DisplayName { get; } = displayName;

    public override string ToString() => DisplayName;
}

public sealed class LanguageManager : INotifyPropertyChanged
{
    public static LanguageManager Instance { get; } = new();

    public event PropertyChangedEventHandler? PropertyChanged;

    public LanguageManager()
    {
        LauncherReadResultDisplay.StringResolver = GetString;
    }

    private string _currentLanguage = "en";

    public static readonly IReadOnlyList<LanguageOption> AvailableLanguages =
    [
        new("en", "English (Default)"),
        new("tr", "Türkçe")
    ];

    public string CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            if (_currentLanguage != value)
            {
                _currentLanguage = value;
                OnPropertyChanged(string.Empty); // Notifies all indexers and properties in WPF
            }
        }
    }

    public void Initialize(AppSettingsStorage storage)
    {
        var settings = storage.Load();
        CurrentLanguage = settings.Language is "tr" ? "tr" : "en";
    }

    public string this[string key] => GetString(key);

    public string GetString(string key) => _currentLanguage switch
    {
        "tr" => GetTurkishString(key),
        _ => GetEnglishString(key)
    };

    /// <summary>
    /// Localizes the language-neutral detection-source strings produced by the Core
    /// launcher readers (e.g. "Registry", "Multi-Drive Scan (C:\)").
    /// </summary>
    public string LocalizeDetectionSource(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return raw ?? string.Empty;

        const string multiDrivePrefix = "Multi-Drive Scan (";
        if (raw.StartsWith(multiDrivePrefix, StringComparison.Ordinal) &&
            raw.EndsWith(")", StringComparison.Ordinal))
        {
            var root = raw[multiDrivePrefix.Length..^1];
            return string.Format(this["DetectionSourceMultiDrive"], root);
        }

        return raw switch
        {
            "Registry" => this["DetectionSourceRegistry"],
            "Registry & Local Cache" => this["DetectionSourceLocalCache"],
            _ => raw
        };
    }

    private static string GetEnglishString(string key) => key switch
    {
        "SettingsTitle" => "ITAD Library Sync — Settings",
        "TabAccountsAndPlatforms" => "Accounts & Platforms",
        "TabSyncAndMappings" => "Sync & Matching",
        "TabSettingsAndLogs" => "Settings & Logs",
        "TabItad" => "ITAD Connection",
        "TabPlatforms" => "Platforms",
        "TabSync" => "Synchronization",
        "TabStats" => "Statistics",
        "TabUnmatched" => "Unmatched Games",
        "TabLogs" => "Logs",
        "TabGeneral" => "General",

        "ItadHeader" => "IsThereAnyDeal Account",
        "ConnectionStatusLabel" => "Connection Status:",
        "StatusConnected" => "Connected",
        "StatusNotConnected" => "Not Connected",
        "UsernameLabel" => "Username:",
        "ConnectBtn" => "Connect to ITAD",
        "DisconnectBtn" => "Disconnect",
        "SyncNowBtn" => "Sync Now",
        "ItadHowItWorksTitle" => "How it works?",
        "ItadHowItWorksText" => "By connecting your ITAD account, your local game libraries will be automatically synced. Game titles are automatically corrected using the Smart Match Engine, and obsolete mismatched entries are purged from your profile.",

        "PlatformTipsTitle" => "Platform Scanning Tips:",
        "PlatformTipsText" => "• Local Platforms (Epic, Ubisoft, Battle.net, EA App): Requires client app installed & run at least once. No account credentials required.\n• Xbox / Microsoft Store: Link your Xbox account below for complete library & Game Pass sync.",
        "ColPlatform" => "Platform",
        "ColEnabled" => "Enabled",
        "ColStatus" => "Status",
        "ColLastSync" => "Last Sync",
        "ColResult" => "Result",
        "ColTest" => "Test",
        "ColDetails" => "Details",
        "BtnTest" => "Test",
        "BtnDetails" => "Details",
        "TestBtnTooltip" => "Quickly scans and tests this platform's game library on your PC or account.",
        "DetailsBtnTooltip" => "Displays detected directory path, scanning method, and full list of found games.",
        "XboxAccountHeader" => "Xbox / Microsoft Store Account",
        "BtnConnectXbox" => "Connect Xbox Account",
        "BtnDisconnectXbox" => "Disconnect Xbox Account",
        "EaAccountHeader" => "EA App Account",
        "BtnConnectEa" => "Connect EA Account",
        "BtnDisconnectEa" => "Disconnect EA Account",
        "PlatformsHeader" => "Game Platforms",
        "PlatformScanInfoTitle" => "Platform Scanning:",
        "PlatformScanInfoText" => "Local platforms (Epic, Ubisoft, Battle.net, EA App) are scanned from your PC's local files. Xbox requires a separate account link below for full coverage.",

        "SyncSettingsHeader" => "Automatic Synchronization Settings",
        "SyncGuideTitle" => "Automatic Sync Guide:",
        "SyncGuideText" => "The app runs silently in the system tray to keep your libraries updated at your selected interval. Newly acquired games are detected automatically.",
        "SyncIntervalLabel" => "Sync Frequency",
        "SyncOnStartupLabel" => "Sync automatically on application startup",
        "ConfirmBeforeSyncLabel" => "Ask for confirmation before manual sync",
        "SyncIntervalTooltip" => "Determines how frequently your game libraries are automatically scanned and sent to ITAD.",
        "SyncOnStartupTooltip" => "Instantly syncs your libraries every time your PC or app starts.",
        "ConfirmBeforeSyncTooltip" => "Displays a preview confirmation window before sending games when you click 'Sync Now'.",

        "StatsHeader" => "Library Statistics & Summary",
        "TotalSyncedGamesLabel" => "Total Synced Games",
        "MatchRateLabel" => "ITAD Match Rate",
        "ActivePlatformsLabel" => "Active Platforms",
        "DuplicateGamesLabel" => "Cross-Platform Games",
        "AutoMatchedLabel" => "Auto-Matched",
        "CustomMappedLabel" => "Custom Mapped",
        "UnmatchedCountLabel" => "Unmatched",
        "PlatformDistributionHeader" => "Platform Library Distribution",
        "SmartInsightsHeader" => "Smart Library Insights",
        "StatTitleTotalGames" => "Full Game Library Details",
        "StatTitleMatchRate" => "ITAD Match Rate & Breakdown Analysis",
        "StatTitleActivePlatforms" => "Platform Launchers Overview",
        "StatTitleDuplicateGames" => "Cross-Platform Duplicate Games",
        "StatSearchPlaceholder" => "Filter by title, store ID, or platform…",
        "ColOwnedPlatforms" => "Owned Platforms",
        "ColScanPath" => "Scan Path & Method",
        "StatusNotDetected" => "Not detected",
        "StatusNotLoggedIn" => "Not logged in",
        "StatusReady" => "Ready",
        "StatusLimited" => "Limited",
        "StatusError" => "Error",
        "ScanSummaryFormat" => "{0} games ({1} owned, {2} wishlist)",
        "ScanSummaryBnetNotice" => "Battle.net local cache may omit uninstalled owned titles",
        "ScanSummaryEaPartial" => "partial library (local fallback)",
        "ScanSummaryEaOnline" => "online EA library",
        "ScanSummaryNoEntries" => "0 games — launcher detected, no readable library entries",
        "ScanSummaryItemSkipped" => "1 item skipped",
        "ScanSummaryItemsSkipped" => "{0} items skipped",
        "ScanSummarySomeItemsSkipped" => "some items skipped",
        "StatSummaryTotalGames" => "{0} games in combined library",
        "StatSummaryMatchRate" => "{0}% ITAD match rate across {1} games",
        "StatSummaryActivePlatforms" => "{0} active launchers configured",
        "StatSummaryDuplicateGames" => "{0} games owned across 2+ platforms",
        "LibPreviewDefaultPath" => "Default Client Path",
        "LibPreviewDefaultSource" => "Registry & Cache",
        "DetectionSourceRegistry" => "Registry",
        "DetectionSourceLocalCache" => "Registry & Local Cache",
        "DetectionSourceMultiDrive" => "Multi-Drive Scan ({0})",
        "ItadAccountDefault" => "ITAD Account",
        "TabCloudSaves" => "Cloud Saves",
        "CloudSavesIntro" => "Backs up your game save files to OneDrive, Google Drive or Dropbox. Your games keep saving to the same place; the files stay safe in your cloud.",
        "CloudProviderLabel" => "Cloud Provider",
        "CloudStep1Title" => "Choose Your Cloud Folder",
        "CloudStep1Hint" => "Pick where your game saves will be backed up. OneDrive, Google Drive or Dropbox just needs to be installed and signed in on this PC.",
        "CloudStep2Title" => "Pick the Games to Back Up",
        "CloudStep2Hint" => "Only games installed on this PC are listed. Tick the ones you want to back up. The save folder is found automatically; if not, use 'Set…' to choose it yourself.",
        "CloudStep3Title" => "Move to Cloud & Manage",
        "CloudStep3Hint" => "Moves the selected games' saves into your cloud folder while the games keep saving to the same place. You can undo everything here at any time.",
        "PlatformsGuide" => "Here you can see every platform this PC scans for games and connect your ITAD account. Click 'Test' next to a platform to preview the games it found.",
        "SyncMappingsGuide" => "This page shows your library sync in real time and lets you fix games that could not be matched on ITAD. Click 'Sync Now' in the card above to run a sync.",
        "SettingsGuide" => "Set how the app behaves: how often it syncs, whether it starts with Windows, the language and more. The log section is only needed when something goes wrong.",
        "CloudProviderRootLabel" => "Root:",
        "CloudProviderOneDrive" => "OneDrive",
        "CloudProviderGoogleDrive" => "Google Drive",
        "CloudProviderDropbox" => "Dropbox",
        "CloudPlatformSteam" => "Steam",
        "CloudLiveLookupLabel" => "Live PCGamingWiki lookup",
        "CloudLiveLookupTooltip" => "When enabled, games without a known save folder are looked up on PCGamingWiki automatically (up to 10 per scan; results cached for 30 days).",
        "CloudStatusLookingUp" => "Looking up save folders on PCGamingWiki…",
        "CloudStatusLookupLimit" => "Live lookup limit reached for this scan.",
        "CloudStatusPcgwFound" => "Found via PCGamingWiki",
        "CloudNoProvider" => "No cloud sync folder detected. Install and sign in to OneDrive, Google Drive or Dropbox first.",
        "CloudStatusReady" => "Ready.",
        "CloudStatusDetecting" => "Scanning installed games…",
        "CloudStatusGamesFormat" => "{0} game(s) found.",
        "CloudStatusMigrating" => "Migrating save folders…",
        "CloudStatusMigratedFormat" => "Migration finished: {0}/{1} succeeded.",
        "CloudStatusMigrated" => "Moved to cloud",
        "CloudStatusFailed" => "Failed",
        "CloudStatusRestored" => "Backup restored.",
        "CloudStatusFound" => "Save folder found",
        "CloudStatusMissing" => "Save folder missing",
        "CloudStatusNoSaveFolder" => "No folder set",
        "CloudStatusAlreadyMigrated" => "Already migrated",
        "CloudStatusOrphanJunction" => "Junction without mapping",
        "CloudStatusStaleMapping" => "Mapping without junction",
        "CloudStatusConflict" => "Target exists",
        "CloudStatusUnavailable" => "Cloud folder unavailable",
        "CloudConfirmMigrateTitle" => "Confirm Cloud Migration",
        "CloudConfirmMigrateText" => "Move {0} selected game(s) to {1}? The save folders will be replaced with junctions.",
        "CloudConfirmRestoreTitle" => "Confirm Restore",
        "CloudConfirmRestoreText" => "Restore the backup of '{0}'? The junction will be removed and your save files moved back to the original location.",
        "CloudNoSelection" => "No games selected.",
        "CloudBrowseTitle" => "Select a save folder",
        "BtnCloudDetect" => "Detect Games",
        "BtnCloudSelectAll" => "Select All",
        "BtnCloudSelectNone" => "Clear",
        "BtnCloudSetFolder" => "Set…",
        "BtnCloudSetFolderTooltip" => "Choose the save folder for this game",
        "BtnCloudPreview" => "Preview",
        "BtnCloudMigrate" => "Move Selected to Cloud",
        "BtnCloudRestore" => "Restore",
        "CloudGamesHeader" => "Installed Games",
        "CloudActiveHeader" => "Games Moved to Cloud",
        "ColCloudSelect" => "Sel.",
        "ColCloudTitle" => "Game",
        "ColCloudPlatform" => "Platform",
        "ColCloudSource" => "Source Folder",
        "ColCloudTarget" => "Cloud Target",
        "ColCloudStatus" => "Status",
        "ColCloudProvider" => "Provider",
        "ColCloudCreated" => "Created",
        "ColCloudAction" => "Action",
        "LibPreviewDetailsHeader" => "Details ({0} items)",
        "StatCardClickTooltip" => "Click to view detailed breakdown",
        "OAuthConnectTitle" => "Connect to IsThereAnyDeal",
        "IntervalDisabled" => "Disabled (Manual Only)",
        "IntervalEvery6Hours" => "Every 6 Hours",
        "IntervalEvery12Hours" => "Every 12 Hours",
        "IntervalEvery24Hours" => "Every 24 Hours",
        "IntervalWeekly" => "Weekly",
        "LogLevelDebug" => "Debug (Detailed Logs)",
        "LogLevelInfo" => "Info (Standard)",
        "LogLevelWarning" => "Warning (Warnings Only)",
        "LogLevelError" => "Error (Errors Only)",
        "PatreonHeader" => "Support the Project on Patreon",
        "PatreonDesc" => "If you enjoy using ITAD Library Sync, support its continued development and upcoming features!",
        "BtnPatreonSupport" => "Support on Patreon ↗",
        "CustomMappingsHeader" => "Custom Game Mappings",
        "ColGameTitle" => "Game Title",
        "ColLocalStoreId" => "Local Store ID",
        "ColTargetItadId" => "Target ITAD ID",
        "BtnDelete" => "Delete",
        "DeleteMappingTooltip" => "Deletes this custom mapping rule.",

        "UnmatchedGuideTitle" => "Manual Match Fix Guide:",
        "UnmatchedGuideText" => "Games found on your local platforms whose titles do not exactly match ITAD's database appear here. Click 'Fix' to map the correct ITAD title.",
        "BtnClearList" => "Clear List",
        "BtnRefresh" => "Refresh",
        "BtnFix" => "Fix",
        "ClearListTooltip" => "Clears the recorded unmatched titles history.",
        "RefreshListTooltip" => "Reloads the unmatched titles list.",
        "ColReason" => "Reason",
        "ColDate" => "Date",
        "ColAction" => "Action",

        "LogsGuideText" => "Live system execution logs for library scanning, matching, and ITAD API sync processes.",
        "BtnOpenLogFolder" => "Open Log Folder",
        "OpenLogFolderTooltip" => "Opens the log files directory in Windows Explorer.",
        "RefreshLogsTooltip" => "Reloads live system logs.",
        "LogFilterTooltip" => "Filter by log level (ALL, INFO, ERROR)",
        "ColTime" => "Time",
        "ColLevel" => "Level",
        "ColMessage" => "Message Details",

        "AppSubtitle" => "IsThereAnyDeal Game Library Synchronization Tool",
        "AppPreferencesHeader" => "Application Preferences",
        "StartWithWindowsLabel" => "Run on Windows startup",
        "CloseToTrayLabel" => "Minimize to system tray when closed",
        "ShowNotificationsLabel" => "Show desktop notifications",
        "LanguageLabel" => "Language / Dil",
        "LogLevelLabel" => "Log Level",
        "AppUpdatesHeader" => "Application Updates",
        "BtnCheckUpdates" => "Check for Updates",
        "BtnDownloadUpdate" => "Download & Update",
        "BtnClose" => "Close",
        "VersionPrefix" => "Version",
        "VersionUpToDate" => "Your version is kept up to date.",

        "StartWithWindowsTooltip" => "Starts the app automatically in the system tray when Windows boots.",
        "CloseToTrayTooltip" => "When you close the window, the app will continue running in the system tray instead of exiting.",
        "ShowNotificationsTooltip" => "Displays Windows desktop notifications when sync completes or encounters an error.",
        "LanguageTooltip" => "Select the application display language (English / Türkçe).",
        "LogLevelTooltip" => "Sets log detail level (Info, Error, Debug).",
        "SystemLogsHeader" => "System Logs",

        "TraySyncNow" => "Sync Now",
        "TraySyncStore" => "Sync {0}",
        "TraySettings" => "Settings…",
        "TrayViewLog" => "View Latest Log File",
        "TrayCheckUpdates" => "Check for Updates…",
        "TrayDisconnect" => "Disconnect ITAD",
        "TrayConnect" => "Connect to ITAD",
        "TrayExit" => "Exit",
        "ExitConfirmText" => "A sync is in progress. Exit anyway?",
        "ExitConfirmTitle" => "Exit ITAD Library Sync",

        // ── Notifications ──
        "NotifSyncComplete" => "Sync complete",
        "NotifSyncFailed" => "Sync failed",
        "NotifSyncPartial" => "Sync completed with errors",
        "NotifNoLaunchers" => "No launchers were synced.",
        "NotifPartialFormat" => "{0} of {1} launchers synced successfully.",
        "NotifConnectedTitle" => "Connected to ITAD",
        "NotifConnectedBody" => "Successfully connected to IsThereAnyDeal.",
        "NotifConnectionFailed" => "Connection failed",
        "NotifDisconnectedTitle" => "Disconnected from ITAD",
        "NotifDisconnectedBody" => "Your ITAD account has been disconnected.",
        "NotifTokenExpiredTitle" => "ITAD session expired",
        "NotifTokenExpiredBody" => "Your IsThereAnyDeal session has expired. Connect again from the tray menu.",
        "NotifReconnectXbox" => "Reconnect Xbox in Settings",
        "NotifUnknownError" => "Unknown error",
        "NotifCollectionLabel" => "collection",
        "NotifWaitlistLabel" => "waitlist",

        // ── Tray Tooltips ──
        "TrayTooltipSyncing" => "ITAD Library Sync — Syncing…",
        "TrayTooltipSuccess" => "ITAD Library Sync — Last sync successful",
        "TrayTooltipPartial" => "ITAD Library Sync — Last sync completed with errors",
        "TrayTooltipError" => "ITAD Library Sync — Last sync failed",
        "TrayTooltipIdle" => "ITAD Library Sync — Idle",
        "TrayUpdateAvailableText" => "A new update is available ({0})!\n\nWould you like to open the download page?",
        "TrayUpdateAvailableTitle" => "Update Available",
        "TrayUpToDateText" => "Your app is on the latest version ({0}).",
        "TrayUpdateCheckTitle" => "Update Check",
        "TrayUpdateCheckFailedText" => "Failed to check for updates: {0}",
        "ErrorTitle" => "Error",
        "CouldNotOpenSettings" => "Could Not Open Settings",

        // ── First Run Wizard ──
        "WizardTitle" => "ITAD Library Sync — Setup Wizard",
        "WizardStepPrefix" => "Step",
        "WizardStepSuffix" => "of 4",
        "WizardWelcomeTitle" => "Welcome",
        "WizardItadTitle" => "Connect ITAD Account",
        "WizardPlatformTitle" => "Platform Detection",
        "WizardReadyTitle" => "Ready to Sync",
        "WizardWelcomeBody" => "Welcome to ITAD Library Sync. This wizard will help you connect your IsThereAnyDeal account, detect game platforms on your system, and run the first sync.",
        "WizardWelcomeSubtext" => "The app runs in the system tray. After setup, it will automatically sync your Epic Games, Ubisoft Connect, Battle.net, EA App and Xbox libraries.",
        "WizardItadBody" => "Connect your IsThereAnyDeal account to sync your libraries.",
        "WizardItadStatusLabel" => "Connection Status:",
        "WizardItadAccountLabel" => "Account:",
        "WizardItadConnectBtn" => "Connect to ITAD",
        "WizardItadNote" => "An authorization window will open in your browser. You must connect your ITAD account before proceeding.",
        "WizardConnected" => "Connected",
        "WizardNotConnected" => "Not Connected",
        "WizardPlatformBody" => "Scanning installed platforms. Results will be displayed below.",
        "WizardColPlatform" => "Platform",
        "WizardColStatus" => "Status",
        "WizardColGames" => "Games Found",
        "WizardReadyBody" => "Setup complete! ITAD Library Sync will run in the system tray.",
        "WizardSyncOnFinish" => "Sync now on finish",
        "WizardSyncOnFinishNote" => "When checked, all active platforms will be synced to your ITAD Collection and Waitlist profiles as soon as the wizard finishes.",
        "WizardBtnBack" => "Back",
        "WizardBtnNext" => "Next",
        "WizardBtnFinish" => "Finish",
        "WizardConnectionFailed" => "Connection Failed",
        "WizardSetupFailed" => "Setup Failed",

        // ── Fix Match Window ──
        "FixMatchTitle" => "Fix Match",
        "FixMatchHeader" => "Fix Match",
        "FixMatchDesc" => "Enter the ITAD Game ID, slug, or paste the full ITAD page URL for this game.",
        "FixMatchGameName" => "Game Title: {0}",
        "FixMatchStoreId" => "Local Store ID: {0}",
        "FixMatchPlatform" => "Platform: {0}",
        "FixMatchTargetLabel" => "ITAD Link or Game Slug / ID:",
        "FixMatchTargetTooltip" => "e.g. syberia-ii or https://isthereanydeal.com/game/syberia-ii/info/",
        "FixMatchSave" => "Save",
        "FixMatchCancel" => "Cancel",
        "FixMatchValidation" => "Please enter a valid ITAD URL, game slug, or Store ID.",
        "FixMatchValidationTitle" => "Warning",

        // ── Sync Progress Inline UI ──
        "SyncProgressTitle" => "ITAD Library Sync — Sync Progress",
        "SyncProgressClose" => "Close",
        "SyncProgressIdle" => "Idle — Ready to sync",
        "SyncProgressSyncing" => "Syncing libraries…",
        "SyncProgressNothing" => "Sync finished — nothing to sync.",
        "SyncProgressSuccess" => "Sync completed — {0}/{1} launcher(s) succeeded.",
        "SyncProgressFailed" => "Sync failed — see log for details.",
        "SyncProgressPartial" => "Sync completed with errors — {0}/{1} launcher(s) succeeded.",
        "SyncInlineHeader" => "Sync Status & Live Progress",

        // ── Library Preview Window ──
        "LibPreviewTitleFormat" => "{0} — Library Preview",
        "LibPreviewSummary" => "Summary: {0}",
        "LibPreviewPath" => "📌 Resolved Path: {0}",
        "LibPreviewMethod" => "🔍 Detection Method: {0}",
        "LibPreviewSearch" => "Search / Filter",
        "SearchUnmatchedTooltip" => "Search unmatched games by title or store ID",
        "SearchLogsTooltip" => "Search log entries",
        "LibPreviewSearchTooltip" => "Search by game title or store ID",
        "LibPreviewOwnedTab" => "Owned ({0})",
        "LibPreviewWishlistTab" => "Wishlist ({0})",
        "LibPreviewGameTitle" => "Game Title",
        "LibPreviewStoreId" => "Store ID",

        // ── SettingsViewModel Dialogs ──
        "VMClearUnmatchedConfirm" => "Clear the unmatched games list?",
        "VMClearUnmatchedTitle" => "Clear List",
        "VMUpdateChecking" => "Checking for updates…",
        "VMUpdateAvailable" => "New version available: {0}",
        "VMUpdateAvailablePrompt" => "New version available ({0})!\n\nWould you like to download and update the application now?",
        "VMUpdateAvailableTitle" => "New Version Available",
        "VMUpToDate" => "You are on the latest version ({0}).",
        "VMUpdateCheckFailed" => "Update check failed: {0}",
        "VMUpdateDownloading" => "Downloading update…",
        "VMUpdateComplete" => "Download complete, restarting application…",
        "VMUpdateDownloadFailed" => "Update download failed: {0}",
        "VMXboxConnectPrompt" => "Connect Xbox account now?",
        "VMXboxConnectTitle" => "Xbox Not Connected",
        "VMEaConnectPrompt" => "Connect your EA account now?",
        "VMEaConnectTitle" => "EA Not Connected",

        // ── App.xaml.cs Error Messages ──
        "AppErrorUnexpected" => "An unexpected error occurred:\n{0}",
        "AppErrorTitle" => "ITAD Library Sync — Error",
        "AppErrorStartup" => "An error occurred while starting the application:\n{0}",
        "AppUpdateNotifTitle" => "ITAD Library Sync — Update Available",
        "AppUpdateNotifBody" => "A new version is available ({0}). Open Settings to download.",

        // ── Unmatched Reason Strings ──
        "UnmatchedReasonNotInCatalog" => "Not found in ITAD catalog",
        "UnmatchedReasonTrackingId" => "Using tracking ID (not matched)",
        "UnmatchedReasonNoApiMatch" => "No match from ITAD lookup",

        // ── Custom Mappings ──
        "CustomMappingsGuideText" => "Games you have manually matched are listed here. You can remove a mapping to let it be re-evaluated on the next sync.",
        "ColMappedId" => "Mapped ID",
        "BtnRemoveMapping" => "Remove this mapping",

        // ── FixMatch Help ──
        "FixMatchHelpPrefix" => "Search for the game on ",
        "FixMatchHelpSuffix" => ". You can paste the full page URL (e.g. https://isthereanydeal.com/game/syberia-ii/info/) or just the slug (syberia-ii).",

        // ── Sync Custom Mappings ──
        "BtnSyncCustomMappings" => "Sync Custom Mappings Now",
        "SyncCustomMappingsTooltip" => "Syncs only your manually matched custom games to your ITAD collection.",
        "VMSyncCustomMappingsNone" => "There are no custom mapped games to sync.",
        "VMSyncCustomMappingsSuccess" => "Successfully synced {0} custom mapped game(s) to your ITAD collection!",
        "VMSyncCustomMappingsTitle" => "Custom Mappings Sync",

        _ => key
    };

    private static string GetTurkishString(string key) => key switch
    {
        "SettingsTitle" => "ITAD Library Sync — Ayarlar",
        "TabAccountsAndPlatforms" => "Hesaplar & Platformlar",
        "TabSyncAndMappings" => "Senkronizasyon & Eşleşmeler",
        "TabSettingsAndLogs" => "Ayarlar & Günlükler",
        "TabItad" => "ITAD Bağlantısı",
        "TabPlatforms" => "Platformlar",
        "TabSync" => "Senkronizasyon",
        "TabStats" => "İstatistikler",
        "TabUnmatched" => "Eşleşmeyenler",
        "TabLogs" => "Loglar",
        "TabGeneral" => "Genel",

        "ItadHeader" => "IsThereAnyDeal Hesabı",
        "ConnectionStatusLabel" => "Bağlantı Durumu:",
        "StatusConnected" => "Bağlı",
        "StatusNotConnected" => "Bağlı Değil",
        "UsernameLabel" => "Kullanıcı Adı:",
        "ConnectBtn" => "ITAD'a Bağlan",
        "DisconnectBtn" => "Bağlantıyı Kes",
        "SyncNowBtn" => "Şimdi Senkronize Et",
        "ItadHowItWorksTitle" => "Nasıl Çalışır?",
        "ItadHowItWorksText" => "ITAD hesabınızı bağlayarak yerel kütüphanelerinizi otomatik aktarabilirsiniz. Oyun isimleri Akıllı Eşleştirme Motoru tarafından otomatik düzeltilir ve eski hatalı kayıtlar profilinizden temizlenir.",

        "PlatformTipsTitle" => "Platform Taraması İpuçları:",
        "PlatformTipsText" => "• Yerel Platformlar (Epic, Ubisoft, Battle.net, EA App): İstemci uygulamasının yüklü ve en az 1 kez çalıştırılmış olması yeterlidir. Ekstra hesap bağlama gerektirmez.\n• Xbox / Microsoft Store: Game Pass ve mağaza oyunlarının tam aktarılması için aşağıdan Xbox hesabınızı bağlamanız önerilir.",
        "ColPlatform" => "Platform",
        "ColEnabled" => "Etkin",
        "ColStatus" => "Durum",
        "ColLastSync" => "Son Senkronizasyon",
        "ColResult" => "Sonuç",
        "ColTest" => "Test",
        "ColDetails" => "Detay",
        "BtnTest" => "Test Et",
        "BtnDetails" => "Detaylar",
        "TestBtnTooltip" => "Bu platformun oyun kütüphanesini bilgisayarınızda veya hesabınızda hızlıca taranıp test edilmesini sağlar.",
        "DetailsBtnTooltip" => "Platformun tespit edildiği klasör yolunu, tarama metodunu ve tespit edilen tüm oyun listesini görüntüler.",
        "XboxAccountHeader" => "Xbox / Microsoft Store Hesabı",
        "BtnConnectXbox" => "Xbox Hesabını Bağla",
        "BtnDisconnectXbox" => "Xbox Hesabını Kopar",
        "EaAccountHeader" => "EA App Hesabı",
        "BtnConnectEa" => "EA Hesabını Bağla",
        "BtnDisconnectEa" => "EA Hesabını Kopar",
        "PlatformsHeader" => "Oyun Platformları",
        "PlatformScanInfoTitle" => "Platform Taraması:",
        "PlatformScanInfoText" => "Yerel platformlar (Epic, Ubisoft, Battle.net, EA App) bilgisayarınızdaki yerel dosyalardan taranmaktadır. Xbox için aşağıdaki hesap bağlantısı gerekmektedir.",

        "SyncSettingsHeader" => "Otomatik Senkronizasyon Ayarları",
        "SyncGuideTitle" => "Otomatik Senkronizasyon Rehberi:",
        "SyncGuideText" => "Seçtiğiniz zaman aralığında uygulama arka planda çalışarak kütüphanelerinizi güncel tutar. Bilgisayarınızı veya oyun istemcilerinizi açıp kapattığınızda yeni alınan oyunlar otomatik algılanır.",
        "SyncIntervalLabel" => "Senkronizasyon Sıklığı",
        "SyncOnStartupLabel" => "Uygulama açılışında otomatik senkronize et",
        "ConfirmBeforeSyncLabel" => "Elle senkronizasyon öncesi onay iste",
        "SyncIntervalTooltip" => "Arka planda oyun kütüphanelerinizin ne sıklıkla otomatik taranacağını ve ITAD'a gönderileceğini belirler.",
        "SyncOnStartupTooltip" => "Bilgisayar veya uygulama her başladığında kütüphanelerinizi anında senkronize eder.",
        "ConfirmBeforeSyncTooltip" => "Şimdi Senkronize Et butonuna bastığınızda aktarılacak oyun listesini onaylamanız için önizleme penceresi açar.",

        "StatsHeader" => "Kütüphane İstatistikleri ve Özet",
        "TotalSyncedGamesLabel" => "Toplam Okunan Oyun",
        "MatchRateLabel" => "ITAD Eşleşme Oranı",
        "ActivePlatformsLabel" => "Aktif Platform",
        "DuplicateGamesLabel" => "Çapraz / Ortak Oyunlar",
        "AutoMatchedLabel" => "Otomatik Eşleşen",
        "CustomMappedLabel" => "Manuel Eşleşen",
        "UnmatchedCountLabel" => "Eşleşmeyen",
        "PlatformDistributionHeader" => "Platform Kütüphane Dağılımı",
        "SmartInsightsHeader" => "Akıllı Kütüphane İçgörüleri",
        "StatTitleTotalGames" => "Tüm Oyun Kütüphanesi Detayı",
        "StatTitleMatchRate" => "ITAD Eşleşme Oranı ve Detaylı Analiz",
        "StatTitleActivePlatforms" => "Platform İstemcileri ve Durum Detayı",
        "StatTitleDuplicateGames" => "Çapraz Platform Ortak Oyun Listesi",
        "StatSearchPlaceholder" => "Oyun adı, mağaza ID veya platforma göre ara…",
        "ColOwnedPlatforms" => "Sahip Olunan Platformlar",
        "ColScanPath" => "Tespit Yolu ve Metodu",
        "StatusNotDetected" => "Tespit edilemedi",
        "StatusNotLoggedIn" => "Oturum açılmadı",
        "StatusReady" => "Hazır",
        "StatusLimited" => "Sınırlı",
        "StatusError" => "Hata",
        "ScanSummaryFormat" => "{0} oyun ({1} sahip olunan, {2} istek listesi)",
        "ScanSummaryBnetNotice" => "Battle.net yerel önbelleği yüklü olmayan oyunları içermeyebilir",
        "ScanSummaryEaPartial" => "kısmi kütüphane (yerel yedek)",
        "ScanSummaryEaOnline" => "çevrimiçi EA kütüphanesi",
        "ScanSummaryNoEntries" => "0 oyun — istemci tespit edildi, okunabilir kayıt yok",
        "ScanSummaryItemSkipped" => "1 öge atlandı",
        "ScanSummaryItemsSkipped" => "{0} öge atlandı",
        "ScanSummarySomeItemsSkipped" => "bazı ögeler atlandı",
        "StatSummaryTotalGames" => "{0} adet okunan oyun kütüphanesi",
        "StatSummaryMatchRate" => "{1} oyunda %{0} ITAD eşleşme oranı",
        "StatSummaryActivePlatforms" => "{0} aktif platform yapılandırıldı",
        "StatSummaryDuplicateGames" => "{0} oyun birden fazla platformda mevcut",
        "LibPreviewDefaultPath" => "Varsayılan İstemci Yolu",
        "LibPreviewDefaultSource" => "Kayıt Defteri ve Önbellek",
        "DetectionSourceRegistry" => "Kayıt Defteri",
        "DetectionSourceLocalCache" => "Kayıt Defteri ve Yerel Önbellek",
        "DetectionSourceMultiDrive" => "Çoklu Sürücü Taraması ({0})",
        "ItadAccountDefault" => "ITAD Hesabı",
        "TabCloudSaves" => "Bulut Kayıtları",
        "CloudSavesIntro" => "Oyun kayıt dosyalarını OneDrive, Google Drive veya Dropbox'a yedekler. Oyunların aynı yere kaydetmeye devam eder; dosyalar bulutunda güvende kalır.",
        "CloudProviderLabel" => "Bulut Sağlayıcı",
        "CloudStep1Title" => "Bulut Klasörünü Seç",
        "CloudStep1Hint" => "Oyun kayıtlarının yedekleneceği yeri seç. OneDrive, Google Drive veya Dropbox'ın bu bilgisayara kurulu ve açık olması yeterli.",
        "CloudStep2Title" => "Yedeklenecek Oyunları Seç",
        "CloudStep2Hint" => "Yalnızca bu bilgisayara kurulu oyunlar listelenir. Yedeklemek istediklerini işaretle. Kayıt klasörü otomatik bulunur; bulunamazsa 'Ayarla…' ile kendin seçebilirsin.",
        "CloudStep3Title" => "Buluta Taşı ve Yönet",
        "CloudStep3Hint" => "Seçilen oyunların kayıtlarını bulut klasörüne taşır; oyunlar aynı yere kaydetmeye devam eder. İstediğin zaman buradan geri alabilirsin.",
        "PlatformsGuide" => "Bu sekmede oyunlarını tarayan platformları görür ve ITAD hesabını bağlarsın. Bir platformun yanındaki 'Test' butonu, bulunan oyunları önizler.",
        "SyncMappingsGuide" => "Bu sayfa kütüphane senkronunu canlı gösterir ve ITAD'de eşleşemeyen oyunları düzeltmene yardımcı olur. Senkronu başlatmak için üstteki 'Şimdi Senkronla' düğmesine tıkla.",
        "SettingsGuide" => "Uygulamanın davranışını buradan ayarlarsın: ne sıklıkla senkronlayacağı, Windows ile birlikte başlayıp başlamayacağı, dil ve daha fazlası. Log bölümü yalnızca bir sorun olduğunda gerekir.",
        "CloudProviderRootLabel" => "Kök:",
        "CloudProviderOneDrive" => "OneDrive",
        "CloudProviderGoogleDrive" => "Google Drive",
        "CloudProviderDropbox" => "Dropbox",
        "CloudPlatformSteam" => "Steam",
        "CloudLiveLookupLabel" => "Canlı PCGamingWiki araması",
        "CloudLiveLookupTooltip" => "Açıkken kayıt klasörü bilinmeyen oyunlar PCGamingWiki'de otomatik aranır (tarama başına en fazla 10; sonuçlar 30 gün önbelleklenir).",
        "CloudStatusLookingUp" => "Kayıt klasörleri PCGamingWiki'de aranıyor…",
        "CloudStatusLookupLimit" => "Bu tarama için canlı arama limitine ulaşıldı.",
        "CloudStatusPcgwFound" => "PCGamingWiki ile bulundu",
        "CloudNoProvider" => "Bulut senkron klasörü bulunamadı. Önce OneDrive, Google Drive veya Dropbox'ı kurup oturum açın.",
        "CloudStatusReady" => "Hazır.",
        "CloudStatusDetecting" => "Kurulu oyunlar taranıyor…",
        "CloudStatusGamesFormat" => "{0} oyun bulundu.",
        "CloudStatusMigrating" => "Kayıt klasörleri taşınıyor…",
        "CloudStatusMigratedFormat" => "Taşıma tamamlandı: {0}/{1} başarılı.",
        "CloudStatusMigrated" => "Buluta taşındı",
        "CloudStatusFailed" => "Başarısız",
        "CloudStatusRestored" => "Yedek geri yüklendi.",
        "CloudStatusFound" => "Kayıt klasörü bulundu",
        "CloudStatusMissing" => "Kayıt klasörü yok",
        "CloudStatusNoSaveFolder" => "Klasör seçilmedi",
        "CloudStatusAlreadyMigrated" => "Zaten taşınmış",
        "CloudStatusOrphanJunction" => "Eşleşmesiz junction",
        "CloudStatusStaleMapping" => "Junctionsuz eşleşme",
        "CloudStatusConflict" => "Hedef mevcut",
        "CloudStatusUnavailable" => "Bulut klasörü kullanılamıyor",
        "CloudConfirmMigrateTitle" => "Bulut Taşımayı Onayla",
        "CloudConfirmMigrateText" => "{0} seçili oyun {1} konumuna taşınsın mı? Kayıt klasörleri junction ile değiştirilecek.",
        "CloudConfirmRestoreTitle" => "Geri Yüklemeyi Onayla",
        "CloudConfirmRestoreText" => "'{0}' yedeği geri yüklensin mi? Junction kaldırılacak ve kayıt dosyalarınız orijinal konuma taşınacak.",
        "CloudNoSelection" => "Oyun seçilmedi.",
        "CloudBrowseTitle" => "Kayıt klasörü seçin",
        "BtnCloudDetect" => "Oyunları Tespit Et",
        "BtnCloudSelectAll" => "Tümünü Seç",
        "BtnCloudSelectNone" => "Temizle",
        "BtnCloudSetFolder" => "Ayarla…",
        "BtnCloudSetFolderTooltip" => "Bu oyun için kayıt klasörünü seçin",
        "BtnCloudPreview" => "Önizle",
        "BtnCloudMigrate" => "Seçilenleri Buluta Taşı",
        "BtnCloudRestore" => "Geri Yükle",
        "CloudGamesHeader" => "Kurulu Oyunlar",
        "CloudActiveHeader" => "Buluta Taşınan Oyunlar",
        "ColCloudSelect" => "Seç.",
        "ColCloudTitle" => "Oyun",
        "ColCloudPlatform" => "Platform",
        "ColCloudSource" => "Kaynak Klasör",
        "ColCloudTarget" => "Bulut Hedefi",
        "ColCloudStatus" => "Durum",
        "ColCloudProvider" => "Sağlayıcı",
        "ColCloudCreated" => "Oluşturma",
        "ColCloudAction" => "İşlem",
        "LibPreviewDetailsHeader" => "Detaylar ({0} öge)",
        "StatCardClickTooltip" => "Detayları görüntülemek için tıklayın",
        "OAuthConnectTitle" => "IsThereAnyDeal'a Bağlan",
        "IntervalDisabled" => "Devre Dışı (Yalnızca Elle)",
        "IntervalEvery6Hours" => "6 Saatte Bir",
        "IntervalEvery12Hours" => "12 Saatte Bir",
        "IntervalEvery24Hours" => "24 Saatte Bir (Günlük)",
        "IntervalWeekly" => "Haftada Bir",
        "LogLevelDebug" => "Hata Ayıklama (Detaylı Log)",
        "LogLevelInfo" => "Bilgi (Standart)",
        "LogLevelWarning" => "Uyarı (Yalnızca Uyarılar)",
        "LogLevelError" => "Hata (Yalnızca Hatalar)",
        "PatreonHeader" => "Patreon Üzerinden Destek Olun",
        "PatreonDesc" => "ITAD Library Sync uygulamasını beğeniyorsanız, geliştirilmesine ve yeni özelliklerin eklenmesine katkıda bulunabilirsiniz!",
        "BtnPatreonSupport" => "Patreon'da Destek Ol ↗",
        "CustomMappingsHeader" => "Özel Eşleşme Kuralları (Custom Mappings)",
        "ColGameTitle" => "Oyun Adı",
        "ColLocalStoreId" => "Yerel Mağaza ID",
        "ColTargetItadId" => "Hedef ITAD ID",
        "BtnDelete" => "Sil",
        "DeleteMappingTooltip" => "Bu özel eşleştirme kuralını siler.",

        "UnmatchedGuideTitle" => "Eşleşmeyen Oyunları Manuel Eşleştirme Rehberi:",
        "UnmatchedGuideText" => "Yerel platformlarınızda bulunan ancak ismi ITAD veritabanındaki resmi ismiyle birebir örtüşmeyen oyunlar burada listelenir. 'Düzelt' butonuna basarak doğru ITAD oyun linkini tanıtabilirsiniz.",
        "BtnClearList" => "Listeyi Temizle",
        "BtnRefresh" => "Yenile",
        "BtnFix" => "Düzelt",
        "ClearListTooltip" => "Eşleşmeyen oyun kayıt geçmişini temizler.",
        "RefreshListTooltip" => "Eşleşmeyen oyunlar listesini yeniden yükler.",
        "ColReason" => "Neden",
        "ColDate" => "Tarih",
        "ColAction" => "Eylem",

        "LogsGuideText" => "Uygulamanın kütüphane tarama, eşleştirme ve ITAD iletişim süreçlerine ait canlı günlüklerdir.",
        "BtnOpenLogFolder" => "Log Klasörünü Aç",
        "OpenLogFolderTooltip" => "Log dosyalarının saklandığı klasörü Windows Gezgini'nde açar.",
        "RefreshLogsTooltip" => "Canlı log akışını yeniden yükler.",
        "LogFilterTooltip" => "Log seviyesine göre filtrele (ALL, INFO, ERROR)",
        "ColTime" => "Zaman",
        "ColLevel" => "Seviye",
        "ColMessage" => "Mesaj Detayı",

        "AppSubtitle" => "IsThereAnyDeal Oyun Kütüphanesi Senkronizasyon Aracı",
        "AppPreferencesHeader" => "Uygulama Tercihleri",
        "StartWithWindowsLabel" => "Windows açılışında çalıştır",
        "CloseToTrayLabel" => "Kapatıldığında sistem tepsisine küçült",
        "ShowNotificationsLabel" => "Masaüstü bildirimlerini göster",
        "LanguageLabel" => "Dil / Language",
        "LogLevelLabel" => "Log Seviyesi",
        "AppUpdatesHeader" => "Uygulama Güncellemeleri",
        "BtnCheckUpdates" => "Güncellemeleri Kontrol Et",
        "BtnDownloadUpdate" => "İndir ve Güncelle",
        "BtnClose" => "Kapat",
        "VersionPrefix" => "Sürüm",
        "VersionUpToDate" => "Sürümünüz güncel tutuluyor.",

        "StartWithWindowsTooltip" => "Bilgisayarınız açıldığında uygulamanın sistem tepsisinde (tray) otomatik başlamasını sağlar.",
        "CloseToTrayTooltip" => "Pencereyi kapattığınızda uygulama tamamen kapanmak yerine sistem tepsisinde çalışmaya devam eder.",
        "ShowNotificationsTooltip" => "Senkronizasyon tamamlandığında veya hata oluştuğunda masaüstü bildirimleri görüntüler.",
        "LanguageTooltip" => "Uygulama görüntüleme dilini seçin (English / Türkçe).",
        "LogLevelTooltip" => "Kaydedilecek log detay seviyesini ayarlar (Bilgi, Hata, Hata Ayıklama).",
        "SystemLogsHeader" => "Sistem Günlükleri",

        "TraySyncNow" => "Şimdi Senkronize Et",
        "TraySyncStore" => "{0} Senkronize Et",
        "TraySettings" => "Ayarlar…",
        "TrayViewLog" => "Son Log Dosyasını Aç",
        "TrayCheckUpdates" => "Güncellemeleri Kontrol Et…",
        "TrayDisconnect" => "ITAD Bağlantısını Kes",
        "TrayConnect" => "ITAD'a Bağlan",
        "TrayExit" => "Çıkış",
        "ExitConfirmText" => "Senkronizasyon devam ediyor. Yine de çıkılsın mı?",
        "ExitConfirmTitle" => "ITAD Library Sync — Çıkış",

        // ── Bildirimler ──
        "NotifSyncComplete" => "Senkronizasyon tamamlandı",
        "NotifSyncFailed" => "Senkronizasyon başarısız",
        "NotifSyncPartial" => "Senkronizasyon hatalarla tamamlandı",
        "NotifNoLaunchers" => "Hiçbir platform senkronize edilmedi.",
        "NotifPartialFormat" => "{1} platformdan {0} tanesi başarıyla senkronize edildi.",
        "NotifConnectedTitle" => "ITAD'a Bağlandı",
        "NotifConnectedBody" => "IsThereAnyDeal hesabına başarıyla bağlanıldı.",
        "NotifConnectionFailed" => "Bağlantı başarısız",
        "NotifDisconnectedTitle" => "ITAD Bağlantısı Kesildi",
        "NotifDisconnectedBody" => "ITAD hesabınızın bağlantısı kesildi.",
        "NotifTokenExpiredTitle" => "ITAD oturumu sona erdi",
        "NotifTokenExpiredBody" => "IsThereAnyDeal oturumunuz sona erdi. Tray menüsünden tekrar bağlanın.",
        "NotifReconnectXbox" => "Ayarlar'dan Xbox'ı yeniden bağlayın",
        "NotifUnknownError" => "Bilinmeyen hata",
        "NotifCollectionLabel" => "koleksiyon",
        "NotifWaitlistLabel" => "istek listesi",

        // ── Tray Tooltip'leri ──
        "TrayTooltipSyncing" => "ITAD Library Sync — Senkronize ediliyor…",
        "TrayTooltipSuccess" => "ITAD Library Sync — Son senkronizasyon başarılı",
        "TrayTooltipPartial" => "ITAD Library Sync — Son senkronizasyon hatalarla tamamlandı",
        "TrayTooltipError" => "ITAD Library Sync — Son senkronizasyon başarısız",
        "TrayTooltipIdle" => "ITAD Library Sync — Boşta",
        "TrayUpdateAvailableText" => "Yeni bir güncelleme mevcut ({0})!\n\nİndirme sayfasını açmak ister misiniz?",
        "TrayUpdateAvailableTitle" => "Güncelleme Mevcut",
        "TrayUpToDateText" => "Uygulamanız en güncel sürümde ({0}).",
        "TrayUpdateCheckTitle" => "Güncelleme Kontrolü",
        "TrayUpdateCheckFailedText" => "Güncelleme kontrolü yapılamadı: {0}",
        "ErrorTitle" => "Hata",
        "CouldNotOpenSettings" => "Ayarlar Açılamadı",

        // ── İlk Kurulum Sihirbazı ──
        "WizardTitle" => "ITAD Library Sync — Kurulum Sihirbazı",
        "WizardStepPrefix" => "Adım",
        "WizardStepSuffix" => "/ 4",
        "WizardWelcomeTitle" => "Hoş Geldiniz",
        "WizardItadTitle" => "ITAD Hesabını Bağla",
        "WizardPlatformTitle" => "Platform Tespiti",
        "WizardReadyTitle" => "Senkronizasyona Hazır",
        "WizardWelcomeBody" => "ITAD Library Sync uygulamasına hoş geldiniz. Bu sihirbaz IsThereAnyDeal hesabınızı bağlamanıza, sisteminizdeki oyun platformlarını tespit etmeye ve ilk senkronizasyonu çalıştırmanıza yardımcı olacaktır.",
        "WizardWelcomeSubtext" => "Uygulama sistem tepsisinde (System Tray) çalışır. Kurulum tamamlandıktan sonra Epic Games, Ubisoft Connect, Battle.net, EA App ve Xbox kütüphanelerinizi otomatik senkronize tutar.",
        "WizardItadBody" => "Kütüphanelerinizi aktarabilmek için IsThereAnyDeal hesabınızı bağlayın.",
        "WizardItadStatusLabel" => "Bağlantı Durumu:",
        "WizardItadAccountLabel" => "Hesap:",
        "WizardItadConnectBtn" => "ITAD'a Bağlan",
        "WizardItadNote" => "Tarayıcıda bir yetkilendirme penceresi açılacaktır. Devam etmeden önce ITAD hesabınızı bağlamalısınız.",
        "WizardConnected" => "Bağlandı",
        "WizardNotConnected" => "Bağlı Değil",
        "WizardPlatformBody" => "Yüklü platformlar taranıyor. Sonuçlar aşağıda görüntülenecektir.",
        "WizardColPlatform" => "Platform",
        "WizardColStatus" => "Durum",
        "WizardColGames" => "Bulunan Oyunlar",
        "WizardReadyBody" => "Kurulum tamamlandı! ITAD Library Sync sistem tepsisinde çalışacaktır.",
        "WizardSyncOnFinish" => "Şimdi senkronize et",
        "WizardSyncOnFinishNote" => "İşaretlendiğinde, kurulum biter bitmez tüm aktif platformlar ITAD Koleksiyon ve İstek Listesi profillerinize aktarılacaktır.",
        "WizardBtnBack" => "Geri",
        "WizardBtnNext" => "İleri",
        "WizardBtnFinish" => "Tamamla",
        "WizardConnectionFailed" => "Bağlantı Başarısız",
        "WizardSetupFailed" => "Kurulum Başarısız",

        // ── Eşleştirme Düzeltme Penceresi ──
        "FixMatchTitle" => "Eşleştirmeyi Düzelt",
        "FixMatchHeader" => "Eşleştirmeyi Düzelt",
        "FixMatchDesc" => "Otomatik bulunamayan bu oyun için ITAD sayfa adresini (URL), slug veya oyun ID değerini girin.",
        "FixMatchGameName" => "Oyun Adı: {0}",
        "FixMatchStoreId" => "Yerel Mağaza ID: {0}",
        "FixMatchPlatform" => "Platform: {0}",
        "FixMatchTargetLabel" => "ITAD Linki veya Oyun Slug / ID:",
        "FixMatchTargetTooltip" => "Örn: syberia-ii veya https://isthereanydeal.com/game/syberia-ii/info/",
        "FixMatchSave" => "Kaydet",
        "FixMatchCancel" => "İptal",
        "FixMatchValidation" => "Lütfen geçerli bir ITAD linki, oyun slug'ı veya Mağaza ID girin.",
        "FixMatchValidationTitle" => "Uyarı",

        // ── Senkronizasyon İlerleme İçi Arayüz ──
        "SyncProgressTitle" => "ITAD Library Sync — Senkronizasyon İlerlemesi",
        "SyncProgressClose" => "Kapat",
        "SyncProgressIdle" => "Boşta — Senkronizasyona hazır",
        "SyncProgressSyncing" => "Kütüphaneler senkronize ediliyor…",
        "SyncProgressNothing" => "Senkronizasyon tamamlandı — aktarılacak platform bulunamadı.",
        "SyncProgressSuccess" => "Senkronizasyon tamamlandı — {0}/{1} platform başarılı.",
        "SyncProgressFailed" => "Senkronizasyon başarısız — detaylar için günlüğe bakın.",
        "SyncProgressPartial" => "Senkronizasyon hatalarla tamamlandı — {0}/{1} platform başarılı.",
        "SyncInlineHeader" => "Senkronizasyon Durumu ve Canlı İlerleme",

        // ── Kütüphane Önizleme Penceresi ──
        "LibPreviewTitleFormat" => "{0} — Kütüphane Önizlemesi",
        "LibPreviewSummary" => "Özet: {0}",
        "LibPreviewPath" => "📌 Tespit Edilen Yol: {0}",
        "LibPreviewMethod" => "🔍 Tespit Metodu: {0}",
        "LibPreviewSearch" => "Arama / Filtreleme",
        "SearchUnmatchedTooltip" => "Eşleşmeyen oyunları başlık veya mağaza ID'sine göre ara",
        "SearchLogsTooltip" => "Log kayıtlarında ara",
        "LibPreviewSearchTooltip" => "Oyun adı veya mağaza ID ara",
        "LibPreviewOwnedTab" => "Sahip Olunanlar ({0})",
        "LibPreviewWishlistTab" => "İstek Listesi ({0})",
        "LibPreviewGameTitle" => "Oyun Adı",
        "LibPreviewStoreId" => "Mağaza ID",

        // ── SettingsViewModel Diyalogları ──
        "VMClearUnmatchedConfirm" => "Eşleşmeyen oyunlar listesi temizlensin mi?",
        "VMClearUnmatchedTitle" => "Listeyi Temizle",
        "VMUpdateChecking" => "Güncellemeler kontrol ediliyor…",
        "VMUpdateAvailable" => "Yeni sürüm mevcut: {0}",
        "VMUpdateAvailablePrompt" => "Yeni sürüm mevcut ({0})!\n\nŞimdi arka planda indirip uygulamayı güncellemek ister misiniz?",
        "VMUpdateAvailableTitle" => "Yeni Sürüm Mevcut",
        "VMUpToDate" => "En güncel sürümü kullanıyorsunuz ({0}).",
        "VMUpdateCheckFailed" => "Güncelleme kontrolü başarısız: {0}",
        "VMUpdateDownloading" => "Güncelleme indiriliyor…",
        "VMUpdateComplete" => "İndirme tamamlandı, uygulama yeniden başlatılıyor…",
        "VMUpdateDownloadFailed" => "Güncelleme indirmesi başarısız: {0}",
        "VMXboxConnectPrompt" => "Xbox hesabınızı şimdi bağlamak ister misiniz?",
        "VMXboxConnectTitle" => "Xbox Bağlı Değil",
        "VMEaConnectPrompt" => "EA hesabınızı şimdi bağlamak ister misiniz?",
        "VMEaConnectTitle" => "EA Bağlı Değil",

        // ── App.xaml.cs Hata Mesajları ──
        "AppErrorUnexpected" => "Uygulamada beklenmeyen bir hata oluştu:\n{0}",
        "AppErrorTitle" => "ITAD Library Sync — Hata",
        "AppErrorStartup" => "Uygulama başlatılırken bir hata oluştu:\n{0}",
        "AppUpdateNotifTitle" => "ITAD Library Sync — Güncelleme Mevcut",
        "AppUpdateNotifBody" => "Yeni bir sürüm mevcut ({0}). İndirmek için Ayarlar'ı açın.",

        // ── Eşleşmeyen Neden Stringleri ──
        "UnmatchedReasonNotInCatalog" => "ITAD kataloğunda bulunamadı",
        "UnmatchedReasonTrackingId" => "Takip ID kullanılıyor (eşleşmedi)",
        "UnmatchedReasonNoApiMatch" => "ITAD sorgulamasında eşleşme yok",

        // ── Özel Eşleştirmeler ──
        "CustomMappingsGuideText" => "Manuel olarak eşleştirdiğiniz oyunlar burada listelenir. Bir eşleştirmeyi kaldırırsanız, sonraki senkronda yeniden değerlendirilir.",
        "ColMappedId" => "Eşlenen ID",
        "BtnRemoveMapping" => "Bu eşleştirmeyi kaldır",

        // ── Eşleştirme Yardımı ──
        "FixMatchHelpPrefix" => "Oyunu ",
        "FixMatchHelpSuffix" => " adresinde arayın. Sayfanın tüm linkini (örn: https://isthereanydeal.com/game/syberia-ii/info/) veya doğrudan linkteki oyun kodunu (syberia-ii) yapıştırabilirsiniz.",

        // ── Özel Eşleştirme Senkronizasyonu ──
        "BtnSyncCustomMappings" => "Şimdi Senkronize Et (Özel Eşleştirmeler)",
        "SyncCustomMappingsTooltip" => "Sadece manuel olarak eşleştirdiğiniz özel oyunları ITAD koleksiyonunuza aktarır.",
        "VMSyncCustomMappingsNone" => "Senkronize edilecek özel eşleştirilmiş oyun bulunamadı.",
        "VMSyncCustomMappingsSuccess" => "{0} adet özel eşleştirilmiş oyun ITAD koleksiyonunuza başarıyla aktarıldı!",
        "VMSyncCustomMappingsTitle" => "Özel Eşleştirme Senkronizasyonu",

        _ => key
    };

    private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
