<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GameCollector.StoreHandlers.EADesktop" Version="4.4.0.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="GameCollector.StoreHandlers.BattleNet" Version="4.4.0.1" />
    <PackageReference Include="GameCollector.StoreHandlers.EGS" Version="4.4.0.1" />
    <PackageReference Include="GameCollector.StoreHandlers.Ubisoft" Version="4.4.0.1" />
    <PackageReference Include="GameCollector.StoreHandlers.Xbox" Version="4.4.0.1" />
    <PackageReference Include="SHA3.Net" Version="2.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="YamlDotNet" Version="15.3.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ITAD.LibrarySync.Core.Tests" />
  </ItemGroup>

</Project>
